webtalk_init -webtalk_dir /home/mario/Documentos/Vivado/Practica2/Practica2.sim/sim_1/behav/xsim/xsim.dir/tb_cerrojo_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Sun Oct 16 10:53:28 2022" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2020.2 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "3064766" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "LIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "c0953279-f892-4945-9981-076d8509114a" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "6c4b63040b8e41d1a746cba35df2e196" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "46" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Arch" -context "user_environment"
webtalk_add_data -client project -key os_release -value "Arch Linux" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "12th Gen Intel(R) Core(TM) i7-1255U" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "4350.245 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "16.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "1 us" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "2" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.01_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "122948_KB" -context "xsim\\usage"
webtalk_transmit -clientid 214299767 -regid "" -xml /home/mario/Documentos/Vivado/Practica2/Practica2.sim/sim_1/behav/xsim/xsim.dir/tb_cerrojo_behav/webtalk/usage_statistics_ext_xsim.xml -html /home/mario/Documentos/Vivado/Practica2/Practica2.sim/sim_1/behav/xsim/xsim.dir/tb_cerrojo_behav/webtalk/usage_statistics_ext_xsim.html -wdm /home/mario/Documentos/Vivado/Practica2/Practica2.sim/sim_1/behav/xsim/xsim.dir/tb_cerrojo_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
