# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/hlocal/TOC2021/PR6/MIPSMulticiclo_R3yModoDepuracion/MIPSMulticiclo_R3yModoDepuracion.srcs/sources_1/ip/mem32x512/mem32x512.xci
# IP: The module: 'mem32x512' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/hlocal/TOC2021/PR6/MIPSMulticiclo_R3yModoDepuracion/MIPSMulticiclo_R3yModoDepuracion.srcs/sources_1/ip/mem32x512/mem32x512_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'mem32x512'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: C:/hlocal/TOC2021/PR6/MIPSMulticiclo_R3yModoDepuracion/MIPSMulticiclo_R3yModoDepuracion.srcs/sources_1/ip/mem32x512/mem32x512.xci
# IP: The module: 'mem32x512' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/hlocal/TOC2021/PR6/MIPSMulticiclo_R3yModoDepuracion/MIPSMulticiclo_R3yModoDepuracion.srcs/sources_1/ip/mem32x512/mem32x512_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'mem32x512'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
