# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/hlocal/TOC2021/PR6/MIPSMulticiclo_R3yModoDepuracion/MIPSMulticiclo_R3yModoDepuracion.srcs/sources_1/ip/DCM_100MHz_10MHz/DCM_100MHz_10MHz.xci
# IP: The module: 'DCM_100MHz_10MHz' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/hlocal/TOC2021/PR6/MIPSMulticiclo_R3yModoDepuracion/MIPSMulticiclo_R3yModoDepuracion.srcs/sources_1/ip/DCM_100MHz_10MHz/DCM_100MHz_10MHz_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'DCM_100MHz_10MHz'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/hlocal/TOC2021/PR6/MIPSMulticiclo_R3yModoDepuracion/MIPSMulticiclo_R3yModoDepuracion.srcs/sources_1/ip/DCM_100MHz_10MHz/DCM_100MHz_10MHz.xdc
# XDC: The top module name and the constraint reference have the same name: 'DCM_100MHz_10MHz'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/hlocal/TOC2021/PR6/MIPSMulticiclo_R3yModoDepuracion/MIPSMulticiclo_R3yModoDepuracion.srcs/sources_1/ip/DCM_100MHz_10MHz/DCM_100MHz_10MHz_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'DCM_100MHz_10MHz'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: C:/hlocal/TOC2021/PR6/MIPSMulticiclo_R3yModoDepuracion/MIPSMulticiclo_R3yModoDepuracion.srcs/sources_1/ip/DCM_100MHz_10MHz/DCM_100MHz_10MHz.xci
# IP: The module: 'DCM_100MHz_10MHz' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/hlocal/TOC2021/PR6/MIPSMulticiclo_R3yModoDepuracion/MIPSMulticiclo_R3yModoDepuracion.srcs/sources_1/ip/DCM_100MHz_10MHz/DCM_100MHz_10MHz_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'DCM_100MHz_10MHz'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/hlocal/TOC2021/PR6/MIPSMulticiclo_R3yModoDepuracion/MIPSMulticiclo_R3yModoDepuracion.srcs/sources_1/ip/DCM_100MHz_10MHz/DCM_100MHz_10MHz.xdc
# XDC: The top module name and the constraint reference have the same name: 'DCM_100MHz_10MHz'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/hlocal/TOC2021/PR6/MIPSMulticiclo_R3yModoDepuracion/MIPSMulticiclo_R3yModoDepuracion.srcs/sources_1/ip/DCM_100MHz_10MHz/DCM_100MHz_10MHz_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'DCM_100MHz_10MHz'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
